CREATE TABLE `auth_user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `password` varchar(128) NOT NULL,
  `last_login` datetime(6) DEFAULT NULL,
  `is_superuser` tinyint(1) NOT NULL,
  `username` varchar(150) NOT NULL,
  `first_name` varchar(150) NOT NULL,
  `last_name` varchar(150) NOT NULL,
  `email` varchar(254) NOT NULL,
  `is_staff` tinyint(1) NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `date_joined` datetime(6) NOT NULL,
  `user_id` bigint NOT NULL,
  `secQues1` varchar(100) DEFAULT NULL,
  `secQues2` varchar(100) DEFAULT NULL,
  `secQues3` varchar(100) DEFAULT NULL,
  `secAns1` varchar(100) DEFAULT NULL,
  `secAns2` varchar(100) DEFAULT NULL,
  `secAns3` varchar(100) DEFAULT NULL,
  `phoneNumber` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3;


-- covidseverityapp.covidapp_comorbidity definition

CREATE TABLE `covidapp_comorbidity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `diabetes` int unsigned NOT NULL,
  `copd` int unsigned NOT NULL,
  `renal` int unsigned NOT NULL,
  `pvd` int unsigned NOT NULL,
  `chf` int unsigned NOT NULL,
  `dementia` int unsigned NOT NULL,
  `cancer` int unsigned NOT NULL,
  `stroke` int unsigned NOT NULL,
  `hepatic` int unsigned NOT NULL,
  `heart` int unsigned NOT NULL,
  `ulcer` int unsigned NOT NULL,
  `paralysis` int unsigned NOT NULL,
  `aids` int unsigned NOT NULL,
  `arthritis` int unsigned NOT NULL,
  `user_id` int NOT NULL,
  `dateFirstSymptoms` date NOT NULL,
  PRIMARY KEY (`id`),
  KEY `covidapp_comorbidity_user_id_27e35ade_fk_auth_user_id` (`user_id`),
  CONSTRAINT `covidapp_comorbidity_user_id_27e35ade_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`),
  CONSTRAINT `covidapp_comorbidity_chk_1` CHECK ((`diabetes` >= 0)),
  CONSTRAINT `covidapp_comorbidity_chk_10` CHECK ((`heart` >= 0)),
  CONSTRAINT `covidapp_comorbidity_chk_11` CHECK ((`ulcer` >= 0)),
  CONSTRAINT `covidapp_comorbidity_chk_12` CHECK ((`paralysis` >= 0)),
  CONSTRAINT `covidapp_comorbidity_chk_13` CHECK ((`aids` >= 0)),
  CONSTRAINT `covidapp_comorbidity_chk_14` CHECK ((`arthritis` >= 0)),
  CONSTRAINT `covidapp_comorbidity_chk_2` CHECK ((`copd` >= 0)),
  CONSTRAINT `covidapp_comorbidity_chk_3` CHECK ((`renal` >= 0)),
  CONSTRAINT `covidapp_comorbidity_chk_4` CHECK ((`pvd` >= 0)),
  CONSTRAINT `covidapp_comorbidity_chk_5` CHECK ((`chf` >= 0)),
  CONSTRAINT `covidapp_comorbidity_chk_6` CHECK ((`dementia` >= 0)),
  CONSTRAINT `covidapp_comorbidity_chk_7` CHECK ((`cancer` >= 0)),
  CONSTRAINT `covidapp_comorbidity_chk_8` CHECK ((`stroke` >= 0)),
  CONSTRAINT `covidapp_comorbidity_chk_9` CHECK ((`hepatic` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


-- covidseverityapp.covidapp_reportvalues definition

CREATE TABLE `covidapp_reportvalues` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `ferritin` double DEFAULT NULL,
  `pct` double DEFAULT NULL,
  `ddimer` double DEFAULT NULL,
  `crp` double DEFAULT NULL,
  `ldh` double DEFAULT NULL,
  `il6` double DEFAULT NULL,
  `lymphocyte` double DEFAULT NULL,
  `neutrophil` double DEFAULT NULL,
  `lympho_neutro_ratio` double DEFAULT NULL,
  `bilirubin` double DEFAULT NULL,
  `temperature` double DEFAULT NULL,
  `oxygensat` double DEFAULT NULL,
  `blood_pressure` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `date_added` date NOT NULL,
  `date_report` date NOT NULL,
  `user_id` int NOT NULL,
  `rtpcrCycleNumber` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `covidapp_reportvalues_user_id_4cd52302_fk_auth_user_id` (`user_id`),
  CONSTRAINT `covidapp_reportvalues_user_id_4cd52302_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


-- covidseverityapp.covidapp_symptoms definition

CREATE TABLE `covidapp_symptoms` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `sore_throat` int unsigned NOT NULL,
  `diarhea` int unsigned NOT NULL,
  `fever` int unsigned NOT NULL,
  `dry_cough` int unsigned NOT NULL,
  `body_ache` int unsigned NOT NULL,
  `headache` int unsigned NOT NULL,
  `runny_nose` int unsigned NOT NULL,
  `nausea` int unsigned NOT NULL,
  `vomiting` int unsigned NOT NULL,
  `anosmia` int unsigned NOT NULL,
  `ageusia` int unsigned NOT NULL,
  `rashes` int unsigned NOT NULL,
  `conjunctivitis` int unsigned NOT NULL,
  `date` date NOT NULL,
  `user_id` int NOT NULL,
  `covidseverity` float DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `covidapp_symptoms_user_id_fbeefed8_fk_auth_user_id` (`user_id`),
  CONSTRAINT `covidapp_symptoms_user_id_fbeefed8_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`),
  CONSTRAINT `covidapp_symptoms_chk_1` CHECK ((`sore_throat` >= 0)),
  CONSTRAINT `covidapp_symptoms_chk_10` CHECK ((`anosmia` >= 0)),
  CONSTRAINT `covidapp_symptoms_chk_11` CHECK ((`ageusia` >= 0)),
  CONSTRAINT `covidapp_symptoms_chk_12` CHECK ((`rashes` >= 0)),
  CONSTRAINT `covidapp_symptoms_chk_13` CHECK ((`conjunctivitis` >= 0)),
  CONSTRAINT `covidapp_symptoms_chk_2` CHECK ((`diarhea` >= 0)),
  CONSTRAINT `covidapp_symptoms_chk_3` CHECK ((`fever` >= 0)),
  CONSTRAINT `covidapp_symptoms_chk_4` CHECK ((`dry_cough` >= 0)),
  CONSTRAINT `covidapp_symptoms_chk_5` CHECK ((`body_ache` >= 0)),
  CONSTRAINT `covidapp_symptoms_chk_6` CHECK ((`headache` >= 0)),
  CONSTRAINT `covidapp_symptoms_chk_7` CHECK ((`runny_nose` >= 0)),
  CONSTRAINT `covidapp_symptoms_chk_8` CHECK ((`nausea` >= 0)),
  CONSTRAINT `covidapp_symptoms_chk_9` CHECK ((`vomiting` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;